### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DewGew**
Typo

### CODE REVIEW

**Comment by DewGew** [comment]
Why dont it get a new row?

**Comment by shivasiddharth** [comment]
Need to add a double space at the end of previous sentence.

**Comment by DewGew** [comment]
Ok.. good to know.
We should give clickatell sms [this](https://github.com/shivasiddharth/GassistPi/commit/f4660e990249c81710f8a531793d358c4a8a7d9d) function also. e.g "send clickatell to 'Bob' then gassistpi ask for message.

**Comment by shivasiddharth** [comment]
Can you raise a PR? Also can you change "clickatell" keyword to "SMS" Google Assistant will have difficulty in deciphering clickatell.

**Comment by DewGew** [comment]
I'll try... :)  Need to download develop branch and test

**Pull request merged**
