### PR TITLE
Updated actions.py to ignore parental warning

### PR DESCRIPTION
**Pull request by grvweb**
Issue: Unable to play playlists like gaana-dj-gaana-international-top-50, gaana-dj-us-top-50 etc.,
Now supports all playlists from gaana.com.

### CODE REVIEW

**Comment by shivasiddharth** [comment]
`parental_warning":0}` is used to find the end of  list. If i merge this PR, Gaana feature will stop working.

**Comment by grvweb** [comment]
> `parental_warning":0}` is used to find the end of list. If i merge this PR, Gaana feature will stop working.

no.. i tested.. 
`parental_warning":(.*)}` will open up wild card. it accept both 0 and 1.

**Comment by grvweb** [comment]
It is just a regular expression.
please test it. it works great..!

**Comment by shivasiddharth** [comment]
I don't have time to test unfortunately. I will merge this commit. For future reference, raise PR for the develop branch.

**Pull request merged**
