### PR TITLE
Fixes the crashes caused by youtube search

### PR DESCRIPTION
**Pull request by Arul-**
- Fixes the way playlist and channel playback links are created
- makes sure the result is not empty
- with the playlist and channel, picks the video randomly so that we can repeat the command to play another song

### CODE REVIEW

**Comment by shivasiddharth** [comment]
Thanks for the PR, has this been tested ? Also, a part needs to be added to the main.py and youtube streaming functions to play playlists or channel's music playback. Currently they look for only a mentioned song.

**Comment by Arul-** [comment]
> has this been tested?
Yes, I'm using it on pi

> Also, a part needs to be added to the main.py and youtube streaming functions to play playlists or channel's music playback.

Yes, this pull request only randomly picks one song from the channel or playlist. Repeating the same command has a chance to play another song.

There are definitely opportunities to tweak and improve, but this will be a good starting point

**Comment by Arul-** [comment]
I have updated my pull request. Now its 100% complete and handles all scenarios and tested :)

**Comment by Arul-** [comment]
here is the `test.py` I was using to check
```python
from youtube_search_engine import youtube_search
from youtube_search_engine import youtube_stream_link
from actions import YouTube_No_Autoplay
from actions import YouTube_Autoplay

# print(youtube_search('stream autoplay meyadha Maan playlist', 10))
YouTube_Autoplay('autoplay stream vishwaroopam 2 playlist')
```

    /home/pi/env/bin/python -u /home/pi/GassistPi/src/test.py

**Comment by shivasiddharth** [comment]
Hi, Can you edit the youtube custom commands section of README as well, mentioning the new capability and  syntaxes etc for the changes that you have made.

**Comment by Arul-** [comment]
Done!

**Pull request merged**
