### PR TITLE
Add MQTT

### PR DESCRIPTION
**Pull request by shivasiddharth**
1. Send commands over MQTT.
2. Commands sent over MQTT with a "custom" prefix is processed as a custom command and the ones without the prefix are processed as commands to the Assistant.
3. Using MQTT Dash app, commands can be sent from phone/tablet to the Pi.

### CODE REVIEW

**Comment by shivasiddharth** [comment]
Fixes #698 Fixes #272

**Comment by reydecopas** [comment]
How do you talk to the phone in order to relay de message to the gassistpi? I mean, how it would be the scene?   1. Ok Google (phone) 2. Turn on domoticz light 3. How is this message translated into mqtt dash app to reach gassapi?

**Comment by shivasiddharth** [comment]
To explain this feature more, I am making a video right now. Once the video goes live, will paste the links here. It's quite hard to explain the functionality by words

**Comment by shivasiddharth** [comment]
You are not speaking to the assistant on phone to clarify things. You are directly sending commands from MQTT Dash app to the Pi.

**Comment by shivasiddharth** [comment]
I have explored a number of different avenues till this date. Without port-forwarding and without webhooks its a nope. 
There is one roundabout way. Whatever query you are making gets registered in the google user data/activity. So you can create a python script to parse the user data and then initiate an action on Pi.

Example of how it will work:
1. On you mobile phone you say "Ok Google, Turn on domoticz device"
2. It will respond back with sorry unable to help. (You can mask this by creating dummy IFTTT applet that does nothing but generates a feedback).
3. The python script will parse you activity/data, then read the command "Turn on domoticz device" and initiate the action.
This happens in a totally closed setup without exposing your devices or Pi to third party apps.

Some people just dont understand that i dont get access to the credentials listed in config.yaml. They think as a project creator i have access to the Pi details. And if i add something lines of code in the script to parse the user data, for sure they are going to hurl "scammer" abuses. Thats the only thing preventing me from implementing it.

**Comment by shivasiddharth** [comment]
@reydecopas If you are free to experiment, Ping me in gitter.

**Pull request merged**
