### PR TITLE
Update gassist-installer.sh

### PR DESCRIPTION
**Pull request by aandroide**
uninstall automatic updates

### CODE REVIEW

**Comment by shivasiddharth** [comment]
Can this be moved to the top ? Before all the installation processes start ?

**Comment by shivasiddharth** [comment]
We could have it here https://github.com/shivasiddharth/GassistPi/blob/da41245cadbf7844defedae6514568dab1a65e14/scripts/gassist-installer.sh#L36

Also, please check as to what happens if this command is executed multiple times.

**Comment by aandroide** [comment]
pi @ raspberrypi: ~ $ sudo apt remove unattended-upgrade -y
Reading package list ... Done
Dependency tree generation
Read status information ... Done
E: The unattended-upgrade package could not be found
pi @ raspberrypi: ~ $ sudo apt remove unattended-upgrade -y
Reading package list ... Done
Dependency tree generation
Read status information ... Done
E: The unattended-upgrade package could not be found

**Comment by aandroide** [comment]
I took your advice

**Comment by shivasiddharth** [comment]
> E: The unattended-upgrade package could not be found

Seems like an error prompt. It could cause the installer script to exit. The script needs to check if the "unattended-upgrade" is present and only then run the command.

**Comment by aandroide** [comment]
I corrected and the scipt was not blocked. see if it's okay.

**Comment by shivasiddharth** [comment]
Have you checked by running the script ? I dont have time now to run the checks. If you can confirm if it works, i will merge the pull request.

**Comment by aandroide** [comment]
yes i created a new sh file to try with my function and right after i added sudo apt update and it ran without errors

**Comment by shivasiddharth** [comment]
What happens if you executed that sh (bash) script multiple times ? I am just making sure that everything is alright.

**Comment by aandroide** [comment]
Cattura0
prova

**Comment by shivasiddharth** [comment]
Ok thanks

**Comment by shivasiddharth** [comment]
Seems like this for Ubuntu system does not work on Pi. I have reverted the changes.

**Pull request merged**
