### PR TITLE
Update main.py

### PR DESCRIPTION
**Pull request by aandroide**
controls all the gassistpi functions with adafruit

### CODE REVIEW

**Comment by aandroide** [comment]
open ifttt, create a new new applet, click on this, search for google assistant, choose option say a phrase with a text ingredient, in what do you say, write custom $, click on create trigger, click on that add the adafruit service, send data to adafruit, on to save choose the textfield ingredient, create action.
in this way all functions can be controlled remotely.
now just tell the assistant on the phone: hey google 'custom play bla bla bla from youtube' and it will work

**Comment by shivasiddharth** [comment]
No need to say add the custom to this. Then the commands will become something like this: "Hey Google, __Some_IFTTT_Keyword__ Custom turn bedroom lights on".

**Comment by shivasiddharth** [comment]
If you add " custom $, click " on create trigger, in IFTTT, custom will not be sent to the adafruit.

**Comment by aandroide** [comment]
you're right I thought it was needed but in the end we can say to google 'gassistpi on the light' you have to maybe then explain this function in the development readme file

**Comment by aandroide** [comment]
but in this way, we can not talk to the native assistant, to say turn on light (google) or what time it is or what time it will be tomorrow, we can only recall our personalized actions.

**Comment by aandroide** [comment]
I prefer to create 2 separate ifttt triggers, one that sends commands to native google and one to our actions with 'custom'

**Comment by aandroide** [comment]
screenshot_20190201-235230_ifttt

just add the word 'custom' here to call our actions

**Comment by shivasiddharth** [comment]
why do you want ifttt for google assistant queries? if you ask what will be the weather to morrow, then the assistant is going to reply on phone. why do you want to send the command to assistant on pi?

**Comment by aandroide** [comment]
yes, in fact the weather is not important. but command the lights of google yes. more than anything else for this reason interested me.

**Comment by shivasiddharth** [comment]
do you want second ifttt for send_text_query function? but why?

**Pull request closed without merging**
