### PR TITLE
Add ability to display graphical output for "Ok Google Hotword assistant" 

### PR DESCRIPTION
**Pull request by shivasiddharth**
Currently only textinput and pushtotalk support display out. This PR will display graphics even for "Ok Google" assistant.

### CODE REVIEW

**Comment by serhatkimya** [comment]
I solved it with magic mirror and now magic mirror shows the video when say "stream i got you'. If want it anyone i will send the code.

**Comment by serhatkimya** [comment]
This changes send link to magicmirror and shows youtube video. must install remote-control module before.

in action.py
def YouTube_No_Autoplay(phrase):
    try:
        urllist=[]
        currenttrackid=0
        idx=phrase.find('show me')
        track=phrase[idx:]
        track=track.replace("'}", "",1)
        track = track.replace('show me','',1)
        #track = track.replace(custom_action_keyword['Dict']['From_youtube'],'',1)
        track=track.strip()
        say("video is starting")
        print(track)
        urlid=youtube_search(track)
        if urlid is not None:
            #fullurl="https://www.youtube.com/watch?v="+urlid
            #audiostream,videostream=youtube_stream_link(fullurl)
            #streamurl=audiostream
            #urllist.append(streamurl)
            #vlcplayer.media_manager(urllist,'YouTube')
            #vlcplayer.youtube_player(currenttrackid)
            rq=requests.get("http://localhost:8080/youtube?id="+urlid)
        else:
            say("Unable to find songs matching your request")
    except:
        say('It is no longer available in youtube')

**Comment by saiedmethal** [comment]
@shivasiddharth  @serhatkimya  will the above Pull work if i edited in the actions.py file,
will it still play the video through Magic Mirror

**Comment by ElectrooPi** [comment]
hi sir i am unable to control ;lights in hindi with the interpretor and can we change its startup sound

**Comment by serhatkimya** [comment]
Electropi, at the main.py find the  /GassistPi........./fb.vaw and change the fb.vaw file and name

**Comment by ElectrooPi** [comment]
sir can you tell me in detail whether we need to use chmod and location of file needs to changed or not

**Comment by ElectrooPi** [comment]
> Electropi, at the main.py find the /GassistPi........./fb.vaw and change the fb.vaw file and name

sir can you tell me in detail whether we need to use chmod and location of file needs toe changed or not

**Comment by samiron7567** [comment]
@shivasiddharth can you also provide an optional document to use Neopixel WS2812B directly without using Wemos D1 Mini please.

**Comment by shivasiddharth** [comment]
A new branch does this work... https://github.com/shivasiddharth/GassistPi/tree/Google-Assistant-SDK-Smart-Screen

**Pull request closed without merging**
