### PR TITLE
Update actions.py

### PR DESCRIPTION
**Pull request by aandroide**
double lines of code copied from line 328

### CODE REVIEW

**Comment by shivasiddharth** [comment]
The change was intentional and is not a mistake.

**Comment by aandroide** [comment]
> Il cambiamento è stato intenzionale e non è un errore.

Yes? But don't work

**Comment by shivasiddharth** [comment]
What is happening ?

**Comment by aandroide** [comment]
> What is happening ?

Don't say. You are secure that the code can work?
`#Text to speech converter with translation
def say(words,sourcelang=None,destinationlang=None):
    if sourcelang!=None and destinationlang!=None:
        sayword=trans(words,destinationlang,sourcelang)
        if TTSChoice=='GoogleCloud':
            gcloudsay(sayword,language)
        elif TTSChoice=='GTTS':
            gttssay(sayword,translanguage,gender)
    else:
        if sourcelang==None:
            sourcelanguage='en'
        else:
            sourcelanguage=sourcelang
        if sourcelanguage!=translanguage:
            sayword=trans(words,translanguage,sourcelanguage)
        else:
            sayword=words
        if TTSChoice=='GoogleCloud':
            gcloudsay(sayword,language)
        elif TTSChoice=='GTTS':
            gttssay(sayword,translanguage,gender)
`

**Comment by shivasiddharth** [comment]
I dont have the Pi with me. It should not cause any problem. Can you manually run and share as to what is happening. It will go into the loop only if you specify the source and destination languages with the "say" function.

**Comment by aandroide** [comment]
> I dont have the Pi with me. It should not cause any problem. Can you manually run and share as to what is happening. It will go into the loop only if you specify the source and destination languages with the "say" function.

on the monitor it does not print any errors, it prints the spoken word but makes no sound. removing that split code everything works fine.

**Comment by shivasiddharth** [comment]
I have made a minor change see if it works now. Still I dont understand what the problem that you are reporting is. Even custom conversation is not working ?

**Comment by aandroide** [comment]
ok I can confirm that with the last change it now works. Before, however, when I said: play "bla bla" from youtube, it printed correctly in Italian on the serial monitor: get the youtube link but it was not pronounced. I hope I have explained myself better. cmq you have solved the error !!!

**Comment by aandroide** [comment]
I also update you on a new error discovered last night:
if i run the assistant manually, i can control the volume from the raspberry.
while when i run the assistant automatically, i cannot increase or decrease the volume, it remains stable on one level.

**Comment by aandroide** [comment]
I'm not talking about the volume of the assistant but the general volume of the raspberry

**Comment by aandroide** [comment]
https://drive.google.com/file/d/1RE0jw3EnWJDutgmf_h15VSPT9RobWw0g/view

I created a video where I show the error. pay no attention to the start-up sound I modified with the ac / dc song

**Comment by shivasiddharth** [comment]
Open a new issue i will see what I can do.

**Pull request closed without merging**
