### PR TITLE
Respeaker patch

### PR DESCRIPTION
**Pull request by shivasiddharth**
Added support for Respeaker HATs.

### CODE REVIEW

**Comment by Hoeby** [comment]
In the general information there is a spoken about the 2 and 4 mic ReSpeaker HAT's.
ReSpeaker also has a 6 mic HAT.

The ReSpeaker wiki gives the next command for installing audio drivers.
`git clone https://github.com/respeaker/seeed-voicecard.git`

When looking to the commands from the patch for GassistPi, the command is
`git clone https://github.com/shivasiddharth/seeed-voicecard`

The names look the same. But gives that a guarantee that the 6 mic version wil work.
Or is it better to keep it with the 2 and 4 mic versions?

**Comment by shivasiddharth** [comment]
I have modified the alsa files. Take a look at the seeed studio's 4 mic asound.conf file and the one from my git. Seeed studio's 4 mic alsa conf does not work with the project. I dont have a 6 mic HAT to test, so its hard for me to test and support.

**Comment by Hoeby** [comment]
i looked at the asound.conf files.
The seeed 4 mic and 6 mic asound.conf files look completly different.
A good chance that the 6 mic will not work in GassistPi, if the 4 mic seeed version also doesn't work whitout using your install. 

This tells me to keep my hands of the 6 mic version. I am not that good with programmering, that without support i can't get it to work.

**Comment by shivasiddharth** [comment]
In the /home/pi/seeed-voicecard directory, try replacing the 6mic conf with this and give it a shot https://raw.githubusercontent.com/shivasiddharth/seeed-voicecard/master/asound_6mic.conf not 100% whether it will work if it works let me know, i will add indicators for that then.

**Pull request merged**
