### PR TITLE
Update main.py

### PR DESCRIPTION
**Pull request by aandroide**
new function sends voice messages from the raspberry to the mobile using pushbullet

### CODE REVIEW

**Comment by aandroide** [comment]
The declaration 'Send_Message_Control' is in the file keywords.yaml

**Comment by shivasiddharth** [comment]
Configuration is taken from config.yaml not the keywords file. You have set xxxxx = 'Enabled" that is not there in config.yaml file

**Comment by shivasiddharth** [comment]
I will leave this PR open. Can you merge all your patches into this patch-20 so all the PRs will become 1 PR

**Comment by shivasiddharth** [comment]
`configuration['Send_Message_Control']['Send_Control']=='Enabled':` these variables should be there in config.yaml file

**Comment by shivasiddharth** [comment]
It's actually easy for you.. you need to create pull requests for yourself and merge all your patches in this patch-20. That is a good practice. If you are finding it difficult, I can reopen all the PRs not a problem.

**Comment by shivasiddharth** [comment]
I have merged the README actions config.yaml PR. the keywords files need to be corrected

**Pull request closed without merging**
