### PR TITLE
update gassistpi-ok-google.service

### PR DESCRIPTION
**Pull request by aandroide**
waiting for updates,return to declare the project id otherwise the language change will not work
https://github.com/googlesamples/assistant-sdk-python/issues/210

### CODE REVIEW

**Comment by shivasiddharth** [comment]
Adding project_id creates multiple device instances. You may have to wait for 0.4.4. Just changing the numbers in the installer will not work, the main.py has to be modified. Humongous amnt of work is being done in another fork alongside for the next update so p[lease wait.

**Comment by aandroide** [comment]
version 0.4.4 has already been released. we are waiting for news

**Comment by shivasiddharth** [comment]
@aandroide , I am aware that 0.4.4 has been released by Google, but you may have to wait for me to reflect it here. GassistPi is being expanded to work in all SBCs and also some bugs are being worked upon. I do appreciate your enthusiasm but, its not like as though the project has crashed and nothing is working in 0.4.3. The current version is pretty much usable and stable.

**Comment by aandroide** [comment]
smoothly agree with you belong the language change that already in 0.4.3 no longer worked and I discovered that strange bug

**Pull request closed without merging**
