### PR TITLE
Recognize facial

### PR DESCRIPTION
**Pull request by aandroide**
added facial recognition with pi.camera

### CODE REVIEW

**Comment by shivasiddharth** [comment]
What does this feature do ?

**Comment by aandroide** [comment]
hello, the camera controls in loop those in front of you, and if the person is recognized, send the name of the person via mqtt from which you can create different functions at will.
For example, I set it up when the cam recognizes me, the assistant asks me if he should do anything for me.

**Comment by shivasiddharth** [comment]
Hi, have you tested and confirmed that this is working?

**Comment by aandroide** [comment]
tonight I try to install everything
from scratch and keep you updated

**Comment by aandroide** [comment]
hello, I fix some errors and reopen the pull request

**Comment by shivasiddharth** [comment]
What happened to this PR ?

**Comment by aandroide** [comment]
I saw that it didn't affect anyone and I gave up

**Pull request closed without merging**
