### PR TITLE
Update actions.py

### PR DESCRIPTION
**Pull request by aandroide**
it-IT runs google cloud

### CODE REVIEW

**Comment by shivasiddharth** [comment]
https://github.com/shivasiddharth/GassistPi/blob/a2cbf57ca0c40c43c17a0b4b5e2f393c5a38fc70/src/actions.py#L221  Translanguage is automatically taken from the language that you set. 

"Translanguage" is only for gtts https://github.com/shivasiddharth/GassistPi/blob/a2cbf57ca0c40c43c17a0b4b5e2f393c5a38fc70/src/actions.py#L306  you can see that for cloud text to speach conversion, i am using the original format.

**Comment by aandroide** [comment]
I do not know why but the player uses gtts if I remove it-IT and put it.
while with that change in the player I see Directory: / tmp /

Terminal control enabled, press 'h' for listing of keys and functions.

Playing MPEG stream 1 of 1: gcloud.mp3 ...

MPEG 2.0 L III cbr32 24000 mono

**Comment by shivasiddharth** [comment]
Its not using gtts. Its actually using cloud only 

> Playing MPEG stream 1 of 1: gcloud.mp3 ...

gcloud.mp3 is the filename that i have assigned to cloud text to speech.

**Comment by aandroide** [comment]
ok, that's right, the problem started to print gcloud only after making that change. in my console api I see 2 requests I have not finished the quota there must be a small error in action.py because if I put back "it" print tmp / say-bad as if it used gtts even if in config I set google cloud

**Comment by shivasiddharth** [comment]
it will use gTTS, even if it is not able to export the environment variable. Open a terminal and type
`export GOOGLE_APPLICATION_CREDENTIALS="path to your google cloud credentials"` Then restart the assistant.
You can take a look at this loop. https://github.com/shivasiddharth/GassistPi/blob/a2cbf57ca0c40c43c17a0b4b5e2f393c5a38fc70/src/actions.py#L50
 this is the part which decides as to what text top speech conversion is used.

**Comment by shivasiddharth** [comment]
When you make the change that you have made in this pull request, A female voice is selected. because the condition is false.
The translanguage from the script is automatically 'it'. So if you check for a condition translanguage=='it-IT' it obviously is going to be false. So instead of using a Male voice, it will use a female voice.
The file names for both gTTS and cloud male voice is the same. Check the lines below. 
https://github.com/shivasiddharth/GassistPi/blob/a2cbf57ca0c40c43c17a0b4b5e2f393c5a38fc70/src/actions.py#L259

https://github.com/shivasiddharth/GassistPi/blob/a2cbf57ca0c40c43c17a0b4b5e2f393c5a38fc70/src/actions.py#L285

So if you are still doubtful as to what is being used, create a new filename path and replace the `malettsfilename` in this line 

https://github.com/shivasiddharth/GassistPi/blob/a2cbf57ca0c40c43c17a0b4b5e2f393c5a38fc70/src/actions.py#L285

**Comment by mcv93us** [comment]
I add myself to the discussion just to make two clarifications: for the Italian language both on smartphone and using gTTS the voice is male while using Google Cloud will be female.
It will be the case to change in autonomy the "pitch" parameter depending on the case.

**Comment by aandroide** [comment]
@shivasiddharth 
export GOOGLE_APPLICATION_CREDENTIALS="path to your google cloud credentials" 
hello Sid, I tried to follow your advice, I opened the terminal is given the suggested command, I restarted the assistant but nothing has changed leaving the original action.py file.
the female continues to speak and the gcloud is not used on the monitor in the player

**Comment by aandroide** [comment]
annotazione 2019-01-14 004511

**Comment by aandroide** [comment]
annotazione 2019-01-14 213107

**Comment by aandroide** [comment]
ok, I found the error in config.yaml in the choice of language, we find:
#Change you language. Default is english
Language:
  Choice: ''
  Language options:
     - 'en-US' # 'English'US
     - 'en-GB' #English GB
     - 'fr-FR' # 'French'
     - 'de-DE' # 'German'
     - 'it-IT' # 'Italian'
     - 'es-ES' # 'Spanish'
     - 'nl-NL' # 'Dutch'
     - 'sv-SE' # 'Swedish'
so I assumed that you had to write "it-IT"
instead just write "it" and the gcloud is used.

**Comment by aandroide** [comment]
https://github.com/shivasiddharth/GassistPi/blob/a2cbf57ca0c40c43c17a0b4b5e2f393c5a38fc70/src/actions.py#L284

if in config.yaml we set language "it", who tells him in that line that must be "it-IT"?

**Comment by aandroide** [comment]
you're right we make clarity:
if in config.yaml imposed the language "it-IT", use "gTTS" and imposed "Evil", I get a male voice correctly but that speaks with low pitch and going to set the pitch to -0, I get the same voice male of the male assistant.
and so far everything is fine even if you need to make the change to the pitch.
If instead in config.yaml imposed the language "it-IT" use "Google Cloud" and imposed "Evil", I realized that the "say" in the player on the serial monitor, shows "Playing WAVE '/ tmp / male-say .wav ", and this makes me think that he is continuing to use" gTTs "because otherwise the player should show" Playing MPEG stream 1 of 1: gcloud.mp3 ... "which he does only if incorrectly in config.yaml imposed the linga in "it" rather than "it-IT" and this last passage seems strange to me. for this reason I thought there was an error in action.py on the language declaration.
I hope I explained myself better.
and I thank you for your explanations and for your time.

**Pull request closed without merging**
