### PR TITLE
Allow settings to be saved

### PR DESCRIPTION
**Pull request by moham96**
1-Settings entered during the installation will be saved in /home/pi/gassistant.info
2-No need to edit the services files manually anymore, the script pulls them from the settings file(/home/pi/gassistant.info)

### CODE REVIEW

**Comment by moham96** [comment]
@shivasiddharth  I edited the messages as you suggested and changed the file name, as for the pi zero installer I combined the two installers in one file, you should test it because I don't have pi zero

**Comment by moham96** [comment]
@shivasiddharth  well I wanted to do it by architecture at first but I don't have armv6 hardware to test, I can probably implement it, what's the output of `uname -m` on an armv6 hardware?

**Comment by moham96** [comment]
@shivasiddharth I implemented your suggestions but before I commit I wanted to ask if you have tested the code on hardware other than armv6 and armv7, x86 for example? and if so should I treat them as armv6 or armv7?

**Comment by shivasiddharth** [comment]
This is what i have used in the other Assistants-Pi installer `if [[ "$(uname -m)" == "armv7l" ]] ; then` So for all others, it will be the pi zero installer.

**Comment by moham96** [comment]
@shivasiddharth check the last commit, I used grep in case the output of `uname -m` comes without the last 'l' (armv7)

**Comment by shivasiddharth** [comment]
Lets not get the directory. Some linux users have this habit of changing directory, it will become a troubleshooting nightmare if each one has the file in a different directory.

**Comment by moham96** [comment]
@shivasiddharth  so I should remove the last commit?

**Comment by shivasiddharth** [comment]
I did not see the the last commit properly, my mistake. Apologies. I shall test it out over the weekend and merge it thereafter.

**Comment by shivasiddharth** [comment]
Just a thought crossed my mind. Now that we are having  a file with all the details, we can parse this in the main.py and pushbutton.py scripts instead of requiring user input.

**Comment by shivasiddharth** [comment]
Can you create a pull request for this branch https://github.com/shivasiddharth/GassistPi/tree/patch-to-parse-project-id-and-model-id-from-file ? I shall work on parsing the credentials in main.py and then merge it with master.

**Pull request closed without merging**
