### PR TITLE
Update GassistPi-pip-requirements.txt

### PR DESCRIPTION
**Pull request by aandroide**
solves the translator's error in other languages ​​other than English

### CODE REVIEW

**Comment by mcv93us** [comment]
If I try to manually update the googletrans library with PIP it gives me the following error: ERROR: Could not open requirements file: [Errno 2] File o directory non esistente: 'googletrans==3.1.0a0'

**Comment by aandroide** [comment]
> Se provo ad aggiornare manualmente la libreria googletrans con PIP mi dà il seguente errore: ERRORE: Impossibile aprire il file dei requisiti: [Errno 2] File o directory non esistente: 'googletrans == 3.1.0a0'
Esegui:
Source env/bin/activate
Pip install googletrans==3.1.0a0

**Comment by mcv93us** [comment]
> > Se provo ad aggiornare manualmente la libreria googletrans con PIP mi dà il seguente errore: ERRORE: Impossibile aprire il file dei requisiti: [Errno 2] File o directory non esistente: 'googletrans == 3.1.0a0'
> > Esegui:
> > Source env/bin/activate
> > Pip install googletrans==3.1.0a0

That's exactly what I did but it gives me the error reported above.

**Comment by aandroide** [comment]
> > > Se provo ad aggiornare manualmente la libreria googletrans con PIP mi dà il seguente errore: ERRORE: Impossibile aprire il file dei requisiti: [Errno 2] File o directory non esistente: 'googletrans == 3.1.0a0'
> > > Esegui:
> > > Source env/bin/activate
> > > Pip install googletrans==3.1.0a0
> 
> That's exactly what I did but it gives me the error reported above.

Esegui: pip --list
And post the output

**Comment by mcv93us** [comment]
Doing "pip --list" doesn't work, I did "pip list" here is the output:
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Package                   Version
------------------------- ------------
adafruit-io               2.1
aftership                 0.2
appdirs                   1.4.3
asn1crypto                1.3.0
beautifulsoup4            4.9.1
bs4                       0.0.1
cachetools                4.1.0
casttube                  0.2.1
certifi                   2020.4.5.2
cffi                      1.14.0
chardet                   3.0.4
Click                     7.0
colorzero                 1.1
cryptography              3.2.1
decorator                 4.4.2
enum34                    1.1.10
feedparser                5.2.1
future                    0.18.2
futures                   3.1.1
gmusicapi                 13.0.0
google-api-core           1.19.1
google-api-python-client  1.8.4
google-assistant-grpc     0.3.0
google-assistant-library  1.1.0
google-assistant-sdk      0.6.0
google-auth               1.16.1
google-auth-httplib2      0.0.3
google-auth-oauthlib      0.4.1
google-cloud-speech       0.36.0
google-cloud-texttospeech 0.3.0
googleapis-common-protos  1.51.0
googletrans               2.3.0
gpiozero                  1.5.1
gpsoauth                  0.4.1
grpcio                    1.29.0
gTTS                      2.2.1
gTTS-token                1.1.4
httplib2                  0.18.1
idna                      2.9
ifaddr                    0.1.6
ipaddress                 1.0.22
kodi-json                 1.0.0
lxml                      4.5.0
MechanicalSoup            0.12.0
mock                      3.0.5
mutagen                   1.44.0
netifaces                 0.10.7
numpy                     1.18.4
oauth2client              4.1.3
oauthlib                  3.1.0
pafy                      0.5.5
paho-mqtt                 1.4.0
pathlib2                  2.3.5
pbr                       5.1.2
pip                       20.3.1
pkg-resources             0.0.0
proboscis                 1.2.6.0
protobuf                  3.11.3
psutil                    5.7.0
pushbullet.py             0.11.0
pvporcupine               1.8.7
pyasn1                    0.4.8
pyasn1-modules            0.2.8
PyAudio                   0.2.11
PyChromecast              5.3.0
pycparser                 2.20
pycryptodomex             3.7.2
pyOpenSSL                 19.1.0
python-dateutil           2.8.1
python-magic              0.4.15
python-vlc                3.0.9113
pytz                      2019.3
pywemo                    0.4.39
PyYAML                    3.13
requests                  2.23.0
requests-oauthlib         1.3.0
RPi.GPIO                  0.6.3
rsa                       4.0
setuptools                47.1.1
six                       1.14.0
sounddevice               0.3.15
SoundFile                 0.10.3.post1
soupsieve                 2.0
spidev                    3.4
spotipy                   2.12.0
tenacity                  6.1.0
uritemplate               3.0.1
urllib3                   1.25.9
validictory               1.1.2
websocket-client          0.57.0
wheel                     0.34.2
youtube-dl                2020.5.29
zeroconf                  0.27.0

**Comment by aandroide** [comment]
you are right I confused the pip list command.
i think the problem is your version of phyton. if i am not mistaken the googletrans update requires python 3.6 but i leave it to sid to answer you more securely.

**Comment by shivasiddharth** [comment]
Do:
```
source env/bin/activate
pip3 uninstall googletrans
pip3 install googletrans==3.1.0a0
```

**Comment by mcv93us** [comment]
Unfortunately it is true you need Python 3.6, after uninstalling it and forcing the update to version 3.1.0a0 it gives me the following error: ERROR: Could not find a version that satisfies the requirement googletrans == 3.1.0a0
ERROR: No matching distribution found for googletrans == 3.1.0a0
I found some guides to upgrade Python to version 3.6.4 on Stretch but I don't know if to risk it.

**Comment by shivasiddharth** [comment]
Open the environment directory and let me know as to what version of python you have. I noticed something. You have a space on either side of `==` which should not be there.

**Comment by mcv93us** [comment]
pi@raspberrypi:~ $ source env/bin/activate
(env) pi@raspberrypi:~ $ python --version
Python 3.5.3
(env) pi@raspberrypi:~ $

**Comment by shivasiddharth** [comment]
@mcv93us , There is no way to update the python version in the environment without creating a new one. We use environments mainly for this feature. If we need to update, then Follow the following steps.

1. Get the list of packages installed
```
source env/bin/activate
pip3 freeze > requirements.txt
```
2. Close the first terminal and open new one to rename the old env folder to something else.
`mv env env_old`
3. Create the new environment
```
sudo apt-get install python3.7-venv
python3.7 -m venv env
```
4. Re-install the old packages
```
source env/bin/activate
pip3 install -r requirements.txt
```

**Comment by mcv93us** [comment]
@shivasiddharth, I created a backup of the SD card in case things go wrong, now I get the list of installed packages as you wrote me and then I try to update to Buster, I will be able to tell you if it works.

**Comment by mcv93us** [comment]
Nothing to do, after three unsuccessful attempts to upgrade from Stretch to Buster I left it alone, on the first reboot everything freezes and the screen remains black.
I tried from Stretch to update Python to version 3.7.9, the installation is successful but then the GassistPI does not start because numpy requires a more recent version of glibc than the one in Stretch and even if I force the upgrade then I find myself with other outdated dependencies to update.
I'll start from 0 with another SD by installing Buster, but it's very annoying!

**Comment by aandroide** [comment]
> I'll start from 0 with another SD by installing Buster, but it's very annoying!

is the best thing!!!

**Pull request closed without merging**
